name: dependencies
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  fimber: ^0.6.1
  get_it: ^7.1.3

  # ui
  google_fonts: 4.0.1
  flutter_screenutil: ^5.9.3
  after_layout: ^1.1.0

  # state management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

  # network and data
  dio: ^5.0.3
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

