name: core
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.19.5
  mockito: ^5.1.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2

flutter:

