name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Activate melos
        run: dart pub global activate melos

      - name: Clean with melos
        run: melos clean

      - name: Bootstrap with melos
        run: melos bs

      - name: Upgrade packages
        run: flutter pub upgrade

      - name: Get packages
        run: flutter pub get

      - name: Activate junitreport
        run: flutter pub global activate junitreport

  test:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Test
        run: melos run test

      - name: Generate coverage
        run: melos run test_results
      
      - name: Generate coverage Report
        run: lcov -r coverage_report/lcov.info '*/__test*__/*' -o coverage_report/lcov_cleaned.info